FROM ubuntu:utopic
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update
RUN apt-get -y install nginx
RUN apt-get -y install supervisor

ADD {{ site_config }} /etc/nginx/sites-enabled/site.conf
RUN rm /etc/nginx/sites-enabled/default

ADD supervisor.conf /etc/supervisor/conf.d/supervisor.conf

EXPOSE 80

CMD ["supervisord", "-n"]
