FROM ubuntu:utopic
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update
RUN apt-get -y install php5-cli
RUN apt-get -y install php5-fpm
RUN apt-get -y install php5-mysql
RUN apt-get -y install supervisor

ADD supervisor.conf /etc/supervisor/conf.d/supervisor.conf
ADD www.conf /etc/php5/fpm/pool.d/www.conf

EXPOSE 9000

CMD ["supervisord", "-n"]
