FROM ubuntu:utopic
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update
RUN apt-get -y install mysql-server
RUN apt-get -y install mysql-client
RUN apt-get -y install supervisor

# setup mysql
RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf
RUN cat /etc/mysql/my.cnf
RUN mkdir -p /var/run/mysqld

ADD set-mysql-password.sh /tmp/set-mysql-password.sh
RUN /bin/sh /tmp/set-mysql-password.sh

ADD supervisor.conf /etc/supervisor/conf.d/supervisor.conf

EXPOSE 3306

CMD ["supervisord", "-n"]
